name: Deploy to Firebase Hosting

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
        working-directory: Orynth
      - run: npm run build
        working-directory: Orynth
      - name: Select deploy channel
        run: |
          if [[ "$GITHUB_REF_NAME" == 'main' ]]; then
            echo "CHANNEL=live" >> $GITHUB_ENV
          else
            echo "CHANNEL=dev-preview" >> $GITHUB_ENV
          fi
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          entryPoint: Orynth
          projectId: orynth-io
          channelId: ${{ env.CHANNEL }}

